/*
  Warnings:

  - The primary key for the `Post` table will be changed. If it partially fails, the table could be left without primary key constraint.

*/
-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "STORE_CATEGORY" ADD VALUE 'TEMPURA';
ALTER TYPE "STORE_CATEGORY" ADD VALUE 'TONKATSU';
ALTER TYPE "STORE_CATEGORY" ADD VALUE 'SUKIYAKI';
ALTER TYPE "STORE_CATEGORY" ADD VALUE 'SOBA';
ALTER TYPE "STORE_CATEGORY" ADD VALUE 'RAMEN';
ALTER TYPE "STORE_CATEGORY" ADD VALUE 'YAKISOBA';
ALTER TYPE "STORE_CATEGORY" ADD VALUE 'OKONOMIYAKI';
ALTER TYPE "STORE_CATEGORY" ADD VALUE 'DONBURI';
ALTER TYPE "STORE_CATEGORY" ADD VALUE 'ODEN';
ALTER TYPE "STORE_CATEGORY" ADD VALUE 'KAISEKI';
ALTER TYPE "STORE_CATEGORY" ADD VALUE 'HAMBAGU';
ALTER TYPE "STORE_CATEGORY" ADD VALUE 'TEPPANYAKI';
ALTER TYPE "STORE_CATEGORY" ADD VALUE 'CURRY';
ALTER TYPE "STORE_CATEGORY" ADD VALUE 'YAKINIKU';
ALTER TYPE "STORE_CATEGORY" ADD VALUE 'NABE';
ALTER TYPE "STORE_CATEGORY" ADD VALUE 'CAFE';
ALTER TYPE "STORE_CATEGORY" ADD VALUE 'IZAKAYA';
ALTER TYPE "STORE_CATEGORY" ADD VALUE 'OTHER';

-- AlterTable
ALTER TABLE "Post" DROP CONSTRAINT "Post_pkey",
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "id" SET DATA TYPE TEXT,
ADD CONSTRAINT "Post_pkey" PRIMARY KEY ("id");
DROP SEQUENCE "Post_id_seq";
